### ISSUE TITLE
[Wrover Kit v4.1] The display doesn't display anything when the SD Card is inserted.

### ISSUE THREAD

**Issue by C47D** [littlevgl/lv_port_esp32#100]
_When the SD Card is inserted into the SD Card holder of the Wrover Kit v4.1, the display doesn't show anything._

This is because the Card Detect (CD) signal is connected to the IO_21 pin, R168 is pulling the IO_21 pin high (to VDD33) and R167 is connected in series between the CD signal and IO_21.
IO_21 is also connected to the D/C signal of the display, so the display D/C pin always gets a logic high, the display controller thinks it's always getting data and no commands.

To solve the issue I removed both R167 and R168, this have the caveat of not being able to detect when the SD Card is inserted on the holder, at least not without soldering a jumper wire connecting the CD signal from the SD Card holder to an unused IO of the ESP32 chip.

![Remove_resistors_from_SD_CARD_CD_signal](https://user-images.githubusercontent.com/11037705/79678123-9f526280-81bd-11ea-9a76-dfc1dbbfe2cd.png)

**Comment by mattiaVDM** [comment]
You just saved me after hours of debugging, i had the same issue. Removing the SD and it finally worked.
