### ISSUE TITLE
ESP get started page

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_port_esp32#115]
Hi,

In the docs of v7 there will be sites for manufacturers and platforms.
For ESP it is here: https://docs.littlevgl.com/v7/en/html/get-started/espressif.html

It's similar to a README. A few lines about ESP, some recommended boards, how to get started, some platform-specific info, a super simple example, etc.

I'd like to ask if somebody has time and energy to write about these things.

**Comment by C47D** [comment]
I would love to do that but I'm pretty busy right now. Have you posted this on the forum?

**Comment by kisvegabor** [comment]
No problem!

> Have you posted this on the forum?
Not yet, I wanted to ask here first.

Thank you anyway! :slightly_smiling_face:
