### ISSUE TITLE
[LV_CONF] Update LV_COLOR_DEPTH based on a menuconfig option

### ISSUE THREAD

**Issue by C47D** [littlevgl/lv_port_esp32#47]
It is now hardcoded, it should be a user configurable option when dealing with other driver configurations?

https://github.com/littlevgl/lv_port_esp32_ili9341/blob/edf5bf19083e911876318c0842c091a6dfdc6d24/components/lvgl/lv_conf.h#L28-L34

**Comment by kisvegabor** [comment]
It can be updated like this:
```c
#ifndef LV_COLOR_DEPTH
#define LV_COLOR_DEPTH     16
#endif
```

**Comment by C47D** [comment]
I think that what @Mat-Alm meant is being able to set the value to 1, 8, 16 or 32 using the menuconfig

**Comment by coredump** [comment]
In a similar question:

Using menuconfig makes it almost never necessary to change stuff on the `lvgl.h` config, but still some stuff that is needed, like enabling themes and fonts. 

What would be an accepted way to change those settings without having to alter the lvgl or add all the possible options to menuconfig?
