### ISSUE TITLE
How make rotation screen (Set portrait orientation) Driver ILI9488

### ISSUE THREAD

**Issue by Djaison** [littlevgl/lv_port_esp32#82]
**ESP-IDF version**
last master

**Development kit used**
ESP-WROOM32

**Development machine OS**
Windows 10

Hello! How can I rotate the screen? I need to set portrait orientation.
I use display with driver ILI9488.

As I understand it, I need to change the starting coordinates of the rendering in the file ili9488.c :

`/* Column addresses  */
	uint8_t xb[] = {
	    (uint8_t) (area->x1 >> 8) & 0xFF,
	    (uint8_t) (area->x1) & 0xFF,
	    (uint8_t) (area->x2 >> 8) & 0xFF,
	    (uint8_t) (area->x2) & 0xFF,
	};
	
	/* Page addresses  */
	uint8_t yb[] = {
	    (uint8_t) (area->y1 >> 8) & 0xFF,
	    (uint8_t) (area->y1) & 0xFF,
	    (uint8_t) (area->y2 >> 8) & 0xFF,
	    (uint8_t) (area->y2) & 0xFF,
	};`

![photo_2020-03-17_12-14-27](https://user-images.githubusercontent.com/16984697/76846739-a64a2600-6849-11ea-803f-f5288e9d4cb5.jpg)

**Comment by Djaison** [comment]
I made corrections to the void ili9488_init (void) function in the ili9488.с file, {ILI9488_CMD_MEMORY_ACCESS_CONTROL, {(0x20 | 0x08)}, 1} I changed it to {ILI9488_CMD_MEMORY_ACCESS_CONxRO} I can add 1 option, {Think} 1 menu} I’ll choose 1 menu}

**Comment by C47D** [comment]
Hi @Djaison,

Can you try swapping the values on this config?
![lvgl_display_size](https://user-images.githubusercontent.com/11037705/76865699-b9003300-6828-11ea-8db7-a653d7bc1d7b.PNG)

If that doesn't work i can add an option to the menuconfig as you've suggested.

Offtopic: Your interface looks really cool :)

**Comment by Djaison** [comment]
> If that doesn't work i can add an option to the menuconfig as you've suggested.

it does not work :)

now it looks like this

![1584452436019](https://user-images.githubusercontent.com/16984697/76872137-add2f480-6874-11ea-8152-f719bd104a63.JPEG)

**Comment by C47D** [comment]
Ok, I will try to add an option to set the display on portrait mode from the menuconfig, but it will be later today.

**Comment by an-erd** [comment]
It would be good to add this option for the ILI9341, too. I just worked on this today and found that for the M5Stack Fire in the file `externals\lv_port_esp32\components\lvgl_esp32_drivers\lvgl_tft\ili9341.c` writing 0x08 (instead of 0x68) to 0x36 worked for . With this the display shows in landscape, with the buttons on the bottom. I used this code:

> #if ILI9341_INVERT_DISPLAY
> 	uint8_t data[] = {0x08};
> 	// this same command also sets rotation (portrait/landscape) and inverts colors.
> 	// https://gist.github.com/motters/38a26a66020f674b6389063932048e4c#file-ili9844_defines-h-L24
> 	ili9341_send_cmd(0x36);
> 	ili9341_send_data(&data, 1);
> #endif

Value taken from ILI9341 datasheet, section 8.2.29. Memory Access Control (36h). Also height and width must be swapped, too. I did it like this in file `externals\lv_port_esp32\components\lvgl\lv_conf.h`
> #define LV_HOR_RES_MAX          (CONFIG_LVGL_DISPLAY_HEIGHT)
> #define LV_VER_RES_MAX          (CONFIG_LVGL_DISPLAY_WIDTH)

**Comment by C47D** [comment]
> It would be good to add this option for the ILI9341, too.

Sure, I will add it later today, I'm at work right now.

**Comment by Djaison** [comment]
I was able to configure the touch to the portrait orientation should also change the default settings in menuconfig, the operating settings such:
![22](https://user-images.githubusercontent.com/16984697/77071171-a3436700-69fc-11ea-88bd-1e123934acb1.png)

P.S. Touch driver is a FT6236

**Comment by C47D** [comment]
It looks really nice :)

> I was able to configure the touch to the portrait orientation should also change the default settings in menuconfig, the operating settings such

We can add a note for that on the README, I don't know if it can be done automagically based on the display orientation.

**Comment by Djaison** [comment]
it can be added to menuсonfig as a function of the orientation of the display, and later I will be able to provide it after checking
